name: news_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 2.25.4
  google_sign_in: 6.2.1
  firebase_auth: 4.17.4
  http: 1.2.0
  get: 4.6.6
  sqflite: 2.3.2
  url_launcher: ^6.2.5
  flutter_svg: 2.0.10+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

